services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - db_data:/var/lib:postgresql/data
  app:
    image: chimera-backend:latest
    container_name: app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: CHIMERA
      DB_PASSWORD: CHIMERA
      DB_NAME: CHIMERA
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  db_data: