name: CI/CD Chimera Backend

on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:
    - main
    - master
    - develop

jobs:
  build-and-test:
    name: Build, Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Build (Compile TypeScript)
        run: npm run build

      - name: Run Tests and Coverage
        run: npm run test:cov

      - name: Docker Build Check
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: chimera:latest